language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
script:
  - cargo test
  - python3 test.py
